//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CarManage.rc
//
#define TIMEID1                         1
#define TIMEID2                         2
#define TIMEID3                         3
#define IDD_ABOUTBOX                    100
#define IDD_CARMANAGE_FORM              101
#define IDR_MAINFRAME                   128
#define IDR_CARMANTYPE                  129
#define IDD_DIALOG1                     130
#define IDD_ROLEDLG                     132
#define IDD_CARDATADLG                  133
#define IDD_LOGDLG                      134
#define IDD_NEWROLEDLG                  135
#define IDD_GPSDLG                      136
#define IDD_TRACEDLG                    137
#define IDD_PLAYBACKDLG                 140
#define IDD_CARINFO                     144
#define IDD_NEWUSERDLG                  145
#define IDD_EDITCARDATADLG              147
#define IDD_MANAGECAR                   148
#define IDD_INOUTDLG                    149
#define IDD_TMDLG                       150
#define IDD_EDITTARGETDLG               151
#define IDC_TAB1                        1000
#define IDC_EXPLORER1                   1001
#define IDC_EDIT1                       1002
#define IDC_BUTTON1                     1003
#define IDC_EDIT7                       1003
#define IDC_BUTTON2                     1004
#define IDC_EDIT3                       1004
#define IDC_EDIT9                       1005
#define IDC_BUTTON3                     1006
#define IDC_EDIT18                      1006
#define IDC_BUTTON4                     1007
#define IDC_EDIT19                      1007
#define IDC_EDIT10                      1008
#define IDC_EDIT11                      1009
#define IDC_EDIT8                       1009
#define IDC_NUMBER                      1009
#define IDC_EDIT12                      1010
#define IDC_EDIT13                      1011
#define IDC_LIST1                       1012
#define IDC_EDIT14                      1014
#define IDC_TERMINALNUM                 1014
#define IDC_EDIT15                      1015
#define IDC_LIST2                       1016
#define IDC_EDIT16                      1016
#define IDC_BUTTON5                     1017
#define IDC_EDIT17                      1017
#define IDC_BUTTON6                     1018
#define IDC_TREE1                       1019
#define IDC_EDIT2                       1020
#define IDC_BUTTON7                     1021
#define IDC_BUTTON8                     1022
#define IDC_STATIC1                     1023
#define IDC_STATIC7                     1024
#define IDC_EDIT4                       1025
#define IDC_EDIT5                       1026
#define IDC_EDIT6                       1027
#define IDC_STATIC2                     1028
#define IDC_STATIC3                     1029
#define IDC_STATIC4                     1030
#define IDC_STATIC5                     1031
#define IDC_STATIC6                     1032
#define IDC_COMBO1                      1033
#define IDC_CARBRAND                    1033
#define IDC_COMBO2                      1034
#define IDC_CARTYPE                     1034
#define IDC_STATIC8                     1035
#define IDC_STATIC9                     1036
#define IDC_STATIC10                    1037
#define IDC_COMBO5                      1038
#define IDC_STATIC11                    1038
#define IDC_COMBO6                      1039
#define IDC_STATICE2                    1040
#define IDC_STATICS1                    1041
#define IDC_MONTHCALENDAR1              1042
#define IDC_MONTHCALENDAR2              1043
#define IDC_DTPICKER1                   1044
#define IDC_DTPICKER2                   1045
#define IDC_COMBO3                      1046
#define IDC_PROGRESS1                   1046
#define IDC_BELONGDEPT                  1046
#define IDC_COMBO4                      1047
#define IDC_STATIC12                    1047
#define IDC_COMBO11                     1048
#define IDC_STATIC13                    1048
#define IDC_COMBO7                      1049
#define IDC_COMBO8                      1050
#define IDC_COMBO12                     1051
#define IDC_WELCOMELAB                  1051
#define IDC_COMBO9                      1052
#define IDC_MODIPW                      1052
#define IDC_COMBO13                     1053
#define IDC_RELOGIN                     1053
#define IDC_COMBO10                     1054
#define IDC_EXIT                        1054
#define IDC_ONE                         1055
#define IDC_TWO                         1056
#define IDC_THREE                       1057
#define IDC_BUYTIME                     1059
#define IDC_CODING                      1061
#define IDC_CARSTATUS                   1062
#define IDC_ENTERTIME                   1063
#define IDC_RADIO1                      1067
#define IDC_RADIO2                      1068
#define IDC_RADIO3                      1069
#define IDC_STARTTIME                   1070
#define IDC_TIME                        1071
#define IDC_DEPT                        1072
#define IDC_PURPOSE                     1073
#define IDC_USER                        1074
#define IDC_ENDTIME                     1075
#define IDC_DEST                        1076
#define IDC_DATETIMEPICKER1             1077
#define IDC_DATETIMEPICKER2             1078
#define IDC_RICHEDIT1                   1079
#define IDC_COMMENTEDIT                 1079
#define IDC_BACKLAB                     1080
#define IDC_TARGETLST                   1087
#define ID_MENUITEM32771                32771
#define ID_MENUITEM32772                32772
#define ID_MENUITEM32773                32773
#define ID_MENUITEM32774                32774

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1089
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
